# nvfetcher.toml
[spicy]
src.github = "zeek/spicy"
fetch.github = "zeek/spicy"
git.fetchSubmodules = true


[broker]
src.github = "zeek/broker"
fetch.github = "zeek/broker"
git.fetchSubmodules = true


[clx]
src.github = "rapidsai/clx"
fetch.github = "rapidsai/clx"
