# nvfetcher.toml
[broker]
src.github = "zeek/broker"
fetch.github = "zeek/broker"
git.fetchSubmodules = true

[clx]
src.github = "rapidsai/clx"
fetch.github = "rapidsai/clx"

[cnmem]
src.github = "NVIDIA/cnmem"
src.git = "https://github.com/NVIDIA/cnmem"
fetch.github = "NVIDIA/cnmem"

#Python Packages
[btest]
src.pypi = "btest"
fetch.pypi = "btest"



#Go Pkgs
[deepsea]
src.manual= "8fdeb3be1965cf31badac68dd0031416dfe1dca3"
fetch.github = "dsnezhkov/deepsea:dafd8c60fcbe33e398a0cea01447f16a61476165"
