name: nix-linux

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v9
      with:
        skip_adding_nixpkgs_channel: false
    - uses: cachix/cachix-action@v6
      with:
        name: nsm-data-analysis
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix-build default.nix
